# Build stage
FROM node:lts-alpine AS build
WORKDIR /app

# ARG VITE_APP_BASE_URL
# ARG VITE_APP_BACKEND_URL
# ARG VITE_APP_AES_SECRET
# ARG VITE_APP_AUTH_PASSKEY
# ARG VITE_APP_HOTKEY1
# ARG VITE_APP_HOTKEY1_COMB
# ARG VITE_APP_HOTKEY2
# ARG VITE_APP_HOTKEY2_COMB
# ARG VITE_APP_HOTKEY3
# ARG VITE_APP_HOTKEY3_COMB
# ARG VITE_APP_HOTKEY4
# ARG VITE_APP_HOTKEY4_COMB
# ARG VITE_APP_HOTKEY5
# ARG VITE_APP_HOTKEY5_COMB

# ENV VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
# ENV VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL}
# ENV VITE_APP_AES_SECRET=${VITE_APP_AES_SECRET}
# ENV VITE_APP_AUTH_PASSKEY=${VITE_APP_AUTH_PASSKEY}
# ENV VITE_APP_HOTKEY1=${VITE_APP_HOTKEY1}
# ENV VITE_APP_HOTKEY1_COMB=${VITE_APP_HOTKEY1_COMB}
# ENV VITE_APP_HOTKEY2=${VITE_APP_HOTKEY2}
# ENV VITE_APP_HOTKEY2_COMB=${VITE_APP_HOTKEY2_COMB}
# ENV VITE_APP_HOTKEY3=${VITE_APP_HOTKEY3}
# ENV VITE_APP_HOTKEY3_COMB=${VITE_APP_HOTKEY3_COMB}
# ENV VITE_APP_HOTKEY4=${VITE_APP_HOTKEY4}
# ENV VITE_APP_HOTKEY4_COMB=${VITE_APP_HOTKEY4_COMB}
# ENV VITE_APP_HOTKEY5=${VITE_APP_HOTKEY5}
# ENV VITE_APP_HOTKEY5_COMB=${VITE_APP_HOTKEY5_COMB}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]