# server {
#     listen 3000;
#     server_tokens off;

#     location /portfolio-v1/ {
#         alias /usr/share/nginx/html/;
#         try_files $uri $uri/ /index.html;
#     }
# }

server {
    listen 3000;
    server_tokens off;

    root /usr/share/nginx/html;
    index index.html;

    location /portfolio-v1/ {
        try_files $uri $uri/ /index.html;
    }
}