name: Deploy Vite App to Pages

on:
  push:
    branches: ["release/production"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      VITE_APP_AES_SECRET: ${{ secrets.VITE_APP_AES_SECRET }}
      VITE_APP_BACKEND_URL: ${{ secrets.VITE_APP_BACKEND_URL }}
      VITE_APP_AUTH_PASSKEY: ${{ secrets.VITE_APP_AUTH_PASSKEY }}
      VITE_APP_HOTKEY1: ${{ secrets.VITE_APP_HOTKEY1 }}
      VITE_APP_HOTKEY1_COMB: ${{ secrets.VITE_APP_HOTKEY1_COMB }}
      VITE_APP_HOTKEY2: ${{ secrets.VITE_APP_HOTKEY2 }}
      VITE_APP_HOTKEY2_COMB: ${{ secrets.VITE_APP_HOTKEY2_COMB }}
      VITE_APP_HOTKEY3: ${{ secrets.VITE_APP_HOTKEY3 }}
      VITE_APP_HOTKEY3_COMB: ${{ secrets.VITE_APP_HOTKEY3_COMB }}
      VITE_APP_HOTKEY4: ${{ secrets.VITE_APP_HOTKEY4 }}
      VITE_APP_HOTKEY4_COMB: ${{ secrets.VITE_APP_HOTKEY4_COMB }}
      VITE_APP_HOTKEY5: ${{ secrets.VITE_APP_HOTKEY5 }}
      VITE_APP_HOTKEY5_COMB: ${{ secrets.VITE_APP_HOTKEY5_COMB }}
      VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          echo "Building project"
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
